name: gflow-sampling
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pip=23.0.1=py39h06a4308_0
  - pyg=2.2.0=py39_torch_1.13.0_cu117
  - python=3.9.16=h7a1cb2a_2
  - pytorch=1.13.1=py3.9_cuda11.7_cudnn8.5.0_0
  - scikit-learn=1.2.1=py39h6a678d5_0
  - scipy=1.10.0=py39h14f4228_1
  - tqdm=4.64.1=py39h06a4308_0
  - pip:
    - ogb==1.3.6
    - typed-argument-parser==1.8.0
    - wandb==0.13.11
